### ISSUE TITLE
GIMP DDS not supported.

### ISSUE THREAD

**Issue by frostbone25** [Telltale-Modding-Group/DDS-D3DTX-Converter#1]
**Opening the extracted .dds textures in GIMP yields an "EOF" error.** 

EOF meaning End of File, trying again will usually yield in the internal DDS plugin crashing in GIMP.

Worth noting that the same exact error is reproduced as well when opening an extracted .dds texture from Telltale Explorer as well. 

**Unfortunately, this is not the fault of Texture Mod Tool or Telltale Explorer**, GIMP recently started supporting .DDS images natively however they don't have all of the formats supported, so therefore it cannot open them. You will need to switch to an alternative software like [Paint.NET](https://www.getpaint.net/download.html#download) or [Photoshop](https://www.adobe.com/products/photoshop.html) with the [Intel Texture Works Plugin](https://software.intel.com/content/www/us/en/develop/articles/intel-texture-works-plugin.html).

**Comment by iMrShadow** [comment]
As of 2024, GIMP has improved their DDS support. Additionally, starting from v2.4, the converter supports DDS files generated by GIMP.

This issue can be considered fixed.
