### ISSUE TITLE
Texture Mods look too bright in game.

### ISSUE THREAD

**Issue by Lilothestitch16** [Telltale-Modding-Group/DDS-D3DTX-Converter#11]
I fixed up my texture edits but they're too bright in game. I used the latest version of the [DDS D3DTX Converter](https://github.com/iMrShadow/DDS-D3DTX-Converter/releases/tag/2.4.0) to replace them but they're too bright for some reason. Any idea how I can fix this?

![20240705221616_1](https://github.com/Telltale-Modding-Group/DDS-D3DTX-Converter/assets/8963276/0d6bb074-eca6-40b3-ae59-5d60c598f395)
![20240705221636_1](https://github.com/Telltale-Modding-Group/DDS-D3DTX-Converter/assets/8963276/57b28916-0b0d-48d0-b65f-07ed13c901d4)
![20240705221645_1](https://github.com/Telltale-Modding-Group/DDS-D3DTX-Converter/assets/8963276/035f0041-384f-4bee-b1cc-4a27999257df)
![20240705221650_1](https://github.com/Telltale-Modding-Group/DDS-D3DTX-Converter/assets/8963276/dc74de43-0479-4a8a-97df-6aa86f79047b)

Here are the samples.

[Kenny.zip](https://github.com/user-attachments/files/16128902/Kenny.zip)
[Matthew.zip](https://github.com/user-attachments/files/16128903/Matthew.zip)
[Sarita.zip](https://github.com/user-attachments/files/16128904/Sarita.zip)
[Walter.zip](https://github.com/user-attachments/files/16128909/Walter.zip)

**Comment by iMrShadow** [comment]
Hello!

The reason why is because you are saving in Linear colourspace. To "darken" the textures, use the sRGB colourspace options. To make sure it's sRGB - the DDS's format must be [FORMAT_NAME]_SRGB.

**Comment by Lilothestitch16** [comment]
How am I supposed to do that?

**Comment by iMrShadow** [comment]
Depends on your image editing software.

I am away from my PC, so I can't tell the exact options. The most sure way would be to google it. I also had some information in the wiki, but it's incomplete.

In Paint.NET, there are save options like: BC3 (DX10, sRGB), BC1 (DX10, sRGB) and others. These are the sRGB save options compared to their linear counterparts - BC1 (DXT1, Linear) and BC3 (DXT5, Linear).

In GIMP there were gamma related settings - you had to check an "Enable Gamma Correction" checkbox and find the sRGB option.

**Comment by Lilothestitch16** [comment]
Thanks. I managed to fix the issue using an old version of the DDS to D3DTX Converter.

**Comment by iMrShadow** [comment]
I'm glad to hear it, but I would like to point out to other users why it worked using the older versions.

Older versions don't make a difference between non-SRGB and SRGB formats. Since TWD:DE textures are originally in SRGB mode, previous versions retained that value. 

In a nutshell, if the texture was originally in SRGB, it would stay the same. If your edited DDS image was saved in BC1 or BC1 SRGB, it wouldn't matter.

**Comment by Lilothestitch16** [comment]
Good point

**Comment by iMrShadow** [comment]
I am closing this issue.
