### ISSUE TITLE
Puzzle Agent 2 file gets corrupted

### ISSUE THREAD

**Issue by webfischi** [Telltale-Modding-Group/DDS-D3DTX-Converter#15]
When converting images dds or png for Puzzle Agent 2 the image gets corrupted

![grafik](https://github.com/user-attachments/assets/66a582a2-9ef0-4ed8-bca9-f98d316fb724)

**Comment by webfischi** [comment]
For some reason the file head gets additional zero bytes

![grafik](https://github.com/user-attachments/assets/09f4a23d-9d99-414e-953a-3dc5e5a4054f)

**Comment by iMrShadow** [comment]
Hi! Thanks for the report. There was a typo in the writing part for this game.

The newest commits fix this, I will upload the new builds soon.

**Comment by iMrShadow** [comment]
Apologies for the long delay, this has been fixed in the latest version! 

I am closing the issue.
