### ISSUE TITLE
no preview and crash

### ISSUE THREAD

**Issue by overdev93** [Telltale-Modding-Group/DDS-D3DTX-Converter#2]
when I load the d3dtx files of back to the future (pc) then the program can't preview the textures and crashes on conversion of them.
the only thing I can do is load the folder with the files in it.

**Comment by frostbone25** [comment]
**This is to be expected**, I wrote in the disclaimer on the main page of this repository that textures from **The Walking Dead Definitive Edition** are only supported for the time being. _(That will change later, but currently working on some of the other tools like Telltale Script Editor rewrite, which will have this texture mod functionality integrated and able to support more games so don't worry)_
