### ISSUE TITLE
d3dtx after converting from .dds doesn't work and looks weird

### ISSUE THREAD

**Issue by PrawyCoD1** [Telltale-Modding-Group/DDS-D3DTX-Converter#4]
Hey,

as in the title. I'm using it for TWD Definitive Series.

![image](https://user-images.githubusercontent.com/70172890/167834092-cc0da6b0-d97a-4a90-9b37-e94d39e96e07.png)

**Comment by PrawyCoD1** [comment]
Also it's weird because everytime i make .dds file without mipmaps your converter shows it have them anyway.
![image](https://user-images.githubusercontent.com/70172890/167836886-80e2bc59-ec1d-4d7d-b181-a10e151097f7.png)

**Comment by PrawyCoD1** [comment]
i've used photoshop, now it's fine but still. 

It's not showing in the game...
![image](https://user-images.githubusercontent.com/70172890/167876624-bd979b5d-4bcb-4ba7-8f8f-c1ec8857b9a7.png)

**Comment by frostbone25** [comment]
For your first response, I see you are using telltale explorer and not my app. I'm not sure how to reply to that as I have no idea what you're doing there other than I see that the telltale explorer internal DDS decoder for the preview fails.

As for your second response, the mipmap count there is 1, meaning that there is only "one" image per se. When the image actually has mipmaps it will almost always be greater than 1 so your fine there.

As for the 3rd response, I am not sure. I am writing a new update to mitigate the room for error that 1.0 of this app has but in there I have a feeling that perhaps the compression type is actually incorrect? However, in your second response, the compression type seems correct for a texture that has an alpha channel... Again I'm rewriting the app for a much better update that solves most of these issues so this will likely get resolved when that comes out.

But however, you did not follow the format I said to follow on the main page when reporting issues - https://github.com/Telltale-Modding-Group/DDS-D3DTX-Converter/wiki/%5BHelp%5D---Reporting-an-Issue-or-Bug - And you have also not provided the problematic files to your issue report so I sadly cannot help you.
