### ISSUE TITLE
Cant launch application after installing .NET Core

### ISSUE THREAD

**Issue by Crazyminer34** [Telltale-Modding-Group/DDS-D3DTX-Converter#5]
After trying to launch it once it told me to install .NET core, then attempted to send me to the install site but didnt. Then I searched it up and installed it and after restarting and trying to launch again I got the same message did I install the right thing and it doesn't work? or did I install the wrong thing and It wont tell me how to install the proper thing?

**Comment by iMrShadow** [comment]
Hello! It's been an year and a half, but with the new update it should be fixed.
